const eventsActionTypes = {
	GET_ALL_EVENTS: "[events] GET_ALL_EVENTS",
	GET_ALL_EVENTS_SUCCESS: "[events] GET_ALL_EVENTS_SUCCESS",
	GET_USER_EVENTS: "[events] GET_USER_EVENTS",
	GET_USER_EVENTS_SUCCESS: "[events] GET_USER_EVENTS_SUCCESS",
	SAVE_EVENT: "[event] SAVE_EVENT",
	SAVE_EVENT_SUCCESS: "[event] SAVE_EVENT_SUCCESS"
};

export default eventsActionTypes;
