const eventsActionTypes = {
	GET_ALL_EVENTS: "[events] GET_ALL_EVENTS",
	GET_ALL_EVENTS_SUCCESS: "[events] GET_ALL_EVENTS_SUCCESS",
	GET_USER_EVENTS: "[events] GET_USER_EVENTS",
	GET_USER_EVENTS_SUCCESS: "[events] GET_USER_EVENTS_SUCCESS",
	SAVE_EVENT: "[events] SAVE_EVENT",
	SAVE_EVENT_SUCCESS: "[events] SAVE_EVENT_SUCCESS",
	GET_CATEGORIES: "[events] GET_CATEGORIES",
	GET_CATEGORIES_SUCCESS: "[events] GET_CATEGORIES_SUCCESS",
	GET_TAGS: "[events] GET_TAGS",
	GET_TAGS_SUCCESS: "[events] GET_TAGS_SUCCESS"
};

export default eventsActionTypes;
