const userActionTypes = {
	GET_PROFILE: "[user] GET_PROFILE",
	GET_PROFILE_SUCCESS: "[user] GET_PROFILE_SUCCESS",
	GET_CURRENT_USER: "[user] GET_CURRENT_USER",
	GET_CURRENT_USER_SUCCESS: "[user] GET_CURRENT_USER_SUCCESS",
	GET_USERS: "[user] GET_USERS",
	GET_USERS_SUCCESS: "[user] GET_USERS_SUCCESS"
};
export default userActionTypes;
