const eventActionTypes = {
	FETCH_EVENT_START: "[event] FETCH_EVENT_START",
	FETCH_EVENT_BY_ID: "[event] FETCH_EVENT_BY_ID",
	FETCH_ALL_EVENTS: "[event] FETCH_ALL_EVENTS",
	FETCH_ALL_EVENTS_SUCCESS: "[event] FETCH_ALL_EVENTS_SUCCESS",
	FETCH_EVENT_BY_ID_SUCCESS: "[event] FETCH_EVENT_BY_ID_SUCCESS",
	EVENT_ACTION_FAILED: "[event] EVENT_ACTION_FAILED",
	ADD_EVENT: "[event] ADD_EVENT",
	ADD_EVENT_INIT: "[event] ADD_EVENT_INIT",
	ADD_EVENT_SUCCESS: "[event] ADD_EVENT_SUCCESS"
};

export default eventActionTypes;
