const eventActionTypes = {
	GET_EVENT_BY_ID: "[event] GET_EVENT_BY_ID",
	GET_EVENT_BY_ID_SUCCESS: "[event] GET_EVENT_BY_ID_SUCCESS",
	ADD_EVENT: "[event] ADD_EVENT",
	GET_ATTENDEES: "[event] GET_ATTENDEES",
	GET_ATTENDEES_SUCCESS: "[event] GET_ATTENDEES_SUCCESS",
	ATTEND_EVENT: "[event] ATTEND_EVENT",
	ATTEND_EVENT_SUCCESS: "[event] ATTEND_EVENT_SUCCESS",
	CANCEL_ATTENDANCE: "[event] CANCEL_ATTENDANCE",
	CANCEL_ATTENDANCE_SUCCESS: "[event] CANCEL_ATTENDANCE_SUCCESS",
	EVENT_PAGE_UNLOADED: "[event] EVENT_PAGE_UNLOADED"
};

export default eventActionTypes;
